{{- $cvmfs_path := .Values.cvmfs_path }}
{{- range $repo := .Values.repositories }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs-config-{{ $repo }}
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvmfs-config-{{ $repo }}
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cvmfs-config-{{ $repo }}
  local:
    path: {{ $cvmfs_path }}/cvmfs-k8s/{{ $repo }}.cern.ch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          -  fake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-config-{{ $repo }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: cvmfs-config-{{ $repo }}
---
{{- end }}
